### ISSUE TITLE
Allow being logged in multiple accounts simultaneously

### ISSUE THREAD

**Issue by ondrejholy** [danigm/fractal#4]
I would like to use Fractal for more accounts since our corporation has an internal server, but seems that only one account/instance can be used at one time.

It would be best to have a possibility to be logged in multiple accounts simultaneously similar how Polari manages multiple IRC networks...

Or at least, it would be nice to have a possibility to open another instance of Fractal with another account. See the similar issue for Revolt:
https://github.com/aperezdc/revolt/issues/83

Or is it possible already somehow?

Thanks for this great client! I don't like Riot.

**Comment by danigm** [comment]
We can do the same as revolt, but we should change also the password store key, because password are stored with the key `fractal`. We should use the ID as secret service key.

**Comment by danigm** [comment]
this github repo is only a mirror, for issues, please report in the gnome gitlab: https://gitlab.gnome.org/danigm/fractal/issues

**Comment by ondrejholy** [comment]
If this is a mirror only, then please [disable issues](https://help.github.com/articles/disabling-issues/) here and possibly add some info about bug reports in README.md, thanks.

**Comment by ondrejholy** [comment]
https://gitlab.gnome.org/danigm/fractal/issues/96
