### ISSUE TITLE
Add tab completion for usernames

### ISSUE THREAD

**Issue by ondrejholy** [danigm/fractal#5]
I really miss username tab completion similar how Polari does it (similar to bash completion).  So, `foo<tab>` to show list of available nicks beginning with foo, or to complete concrete nick if there is only one.

**Comment by danigm** [comment]
this github repo is only a mirror, for issues, please report in the gnome gitlab: https://gitlab.gnome.org/danigm/fractal/issues

**Comment by ondrejholy** [comment]
https://gitlab.gnome.org/danigm/fractal/issues/97
